import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Reference mockups from Claude Design — read as a visual spec, never built.
    "design/**",
    // Generated by `prisma generate`.
    "src/generated/**",
  ]),
  {
    rules: {
      // Every service method takes `viewer` first, whether or not that particular
      // method needs it. The uniform signature is the point — it makes an unguarded
      // method obvious — so an underscore-prefixed parameter is deliberate, not dead.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
]);

export default eslintConfig;
